version: 1.0.{build}
build_script:
- cmd: >-
    npm install -g gulp

    npm install

    gulp package:windows

    cd release

    mkdir electron-mattermost-win32

    move electron-mattermost-win32-ia32 electron-mattermost-win32\electron-mattermost-win32

    mkdir electron-mattermost-win64

    move electron-mattermost-win32-x64 electron-mattermost-win64\electron-mattermost-win64
artifacts:
- path: release\electron-mattermost-win32
- path: release\electron-mattermost-win64